name = "rag"
main = "src/index.ts"
compatibility_date = "2024-10-28"

[ai]
binding = "AI"

[vars]
ENABLE_TEXT_SPLITTING = true

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "hippocampus"
database_id = "7aca1f6a-ba0d-4395-b6f4-5803211d03d9"

[[vectorize]]
binding = "VECTORIZE"
index_name = "neocortex"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"