name = "rag"
main = "src/index.ts"
compatibility_date = "2024-10-28"

[ai]
binding = "AI"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DATABASE"
database_name = "ai-example"
database_id = "2a210384-148b-4c31-bbad-c2873f649f9c"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "tutorial-index-768"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"
